//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/", IsNullable = false)]
public partial class policy
{

    private CtmLookup covertypeField;

    private System.DateTime coverstartdateField;

    private CtmLookup paymentfrequencyField;

    private PolicyHolders policyholdersField;

    private ContactDetails contactdetailsField;

    private Property propertyField;

    private object[] itemsField;

    /// <remarks/>
    public CtmLookup covertype
    {
        get
        {
            return this.covertypeField;
        }
        set
        {
            this.covertypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime coverstartdate
    {
        get
        {
            return this.coverstartdateField;
        }
        set
        {
            this.coverstartdateField = value;
        }
    }

    /// <remarks/>
    public CtmLookup paymentfrequency
    {
        get
        {
            return this.paymentfrequencyField;
        }
        set
        {
            this.paymentfrequencyField = value;
        }
    }

    /// <remarks/>
    public PolicyHolders policyholders
    {
        get
        {
            return this.policyholdersField;
        }
        set
        {
            this.policyholdersField = value;
        }
    }

    /// <remarks/>
    public ContactDetails contactdetails
    {
        get
        {
            return this.contactdetailsField;
        }
        set
        {
            this.contactdetailsField = value;
        }
    }

    /// <remarks/>
    public Property property
    {
        get
        {
            return this.propertyField;
        }
        set
        {
            this.propertyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("buildingscover", typeof(BuildingsCover))]
    [System.Xml.Serialization.XmlElementAttribute("contentscover", typeof(ContentsCover))]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class CtmLookup
{

    private string codeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class HouseholdSpecifiedItem
{

    private AbiLookup typeField;

    private string descriptionField;

    private string currentvalueField;

    private bool awayfromhomeField;

    /// <remarks/>
    public AbiLookup type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    public string currentvalue
    {
        get
        {
            return this.currentvalueField;
        }
        set
        {
            this.currentvalueField = value;
        }
    }

    /// <remarks/>
    public bool awayfromhome
    {
        get
        {
            return this.awayfromhomeField;
        }
        set
        {
            this.awayfromhomeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class AbiLookup
{

    private string abicodeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string abicode
    {
        get
        {
            return this.abicodeField;
        }
        set
        {
            this.abicodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class HouseholdAlarm
{

    private bool alarmprofessionalfittedField;

    private bool approvedcompanyField;

    /// <remarks/>
    public bool alarmprofessionalfitted
    {
        get
        {
            return this.alarmprofessionalfittedField;
        }
        set
        {
            this.alarmprofessionalfittedField = value;
        }
    }

    /// <remarks/>
    public bool approvedcompany
    {
        get
        {
            return this.approvedcompanyField;
        }
        set
        {
            this.approvedcompanyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class HouseholdSecurity
{

    private CtmLookup maindoorField;

    private CtmLookup slidingdoorField;

    private CtmLookup otherextdoorField;

    private bool neighbourhoodwatchField;

    private bool windowsField;

    private HouseholdAlarm alarmField;

    /// <remarks/>
    public CtmLookup maindoor
    {
        get
        {
            return this.maindoorField;
        }
        set
        {
            this.maindoorField = value;
        }
    }

    /// <remarks/>
    public CtmLookup slidingdoor
    {
        get
        {
            return this.slidingdoorField;
        }
        set
        {
            this.slidingdoorField = value;
        }
    }

    /// <remarks/>
    public CtmLookup otherextdoor
    {
        get
        {
            return this.otherextdoorField;
        }
        set
        {
            this.otherextdoorField = value;
        }
    }

    /// <remarks/>
    public bool neighbourhoodwatch
    {
        get
        {
            return this.neighbourhoodwatchField;
        }
        set
        {
            this.neighbourhoodwatchField = value;
        }
    }

    /// <remarks/>
    public bool windows
    {
        get
        {
            return this.windowsField;
        }
        set
        {
            this.windowsField = value;
        }
    }

    /// <remarks/>
    public HouseholdAlarm alarm
    {
        get
        {
            return this.alarmField;
        }
        set
        {
            this.alarmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class ContentsCover
{

    private CtmLookup claimfreeyearsField;

    private string suminsuredField;

    private string highriskitemvalueField;

    private string personalpossessioncoverField;

    private bool accidentaldamageField;

    private CtmLookup voluntaryexcessField;

    private HouseholdSecurity securityField;

    private HouseholdSpecifiedItem[] specifieditemsField;

    /// <remarks/>
    public CtmLookup claimfreeyears
    {
        get
        {
            return this.claimfreeyearsField;
        }
        set
        {
            this.claimfreeyearsField = value;
        }
    }

    /// <remarks/>
    public string suminsured
    {
        get
        {
            return this.suminsuredField;
        }
        set
        {
            this.suminsuredField = value;
        }
    }

    /// <remarks/>
    public string highriskitemvalue
    {
        get
        {
            return this.highriskitemvalueField;
        }
        set
        {
            this.highriskitemvalueField = value;
        }
    }

    /// <remarks/>
    public string personalpossessioncover
    {
        get
        {
            return this.personalpossessioncoverField;
        }
        set
        {
            this.personalpossessioncoverField = value;
        }
    }

    /// <remarks/>
    public bool accidentaldamage
    {
        get
        {
            return this.accidentaldamageField;
        }
        set
        {
            this.accidentaldamageField = value;
        }
    }

    /// <remarks/>
    public CtmLookup voluntaryexcess
    {
        get
        {
            return this.voluntaryexcessField;
        }
        set
        {
            this.voluntaryexcessField = value;
        }
    }

    /// <remarks/>
    public HouseholdSecurity security
    {
        get
        {
            return this.securityField;
        }
        set
        {
            this.securityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
    public HouseholdSpecifiedItem[] specifieditems
    {
        get
        {
            return this.specifieditemsField;
        }
        set
        {
            this.specifieditemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Hazards
{

    private bool everfloodedField;

    private bool within400mofwaterField;

    private bool crackingField;

    private bool talltreesField;

    private bool buildingworkField;

    private bool subsidenceField;

    private bool underpinningField;

    private bool ongoingdamageField;

    /// <remarks/>
    public bool everflooded
    {
        get
        {
            return this.everfloodedField;
        }
        set
        {
            this.everfloodedField = value;
        }
    }

    /// <remarks/>
    public bool within400mofwater
    {
        get
        {
            return this.within400mofwaterField;
        }
        set
        {
            this.within400mofwaterField = value;
        }
    }

    /// <remarks/>
    public bool cracking
    {
        get
        {
            return this.crackingField;
        }
        set
        {
            this.crackingField = value;
        }
    }

    /// <remarks/>
    public bool talltrees
    {
        get
        {
            return this.talltreesField;
        }
        set
        {
            this.talltreesField = value;
        }
    }

    /// <remarks/>
    public bool buildingwork
    {
        get
        {
            return this.buildingworkField;
        }
        set
        {
            this.buildingworkField = value;
        }
    }

    /// <remarks/>
    public bool subsidence
    {
        get
        {
            return this.subsidenceField;
        }
        set
        {
            this.subsidenceField = value;
        }
    }

    /// <remarks/>
    public bool underpinning
    {
        get
        {
            return this.underpinningField;
        }
        set
        {
            this.underpinningField = value;
        }
    }

    /// <remarks/>
    public bool ongoingdamage
    {
        get
        {
            return this.ongoingdamageField;
        }
        set
        {
            this.ongoingdamageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class BuildingsCover
{

    private CtmLookup claimfreeyearsField;

    private string suminsuredField;

    private bool accidentaldamageField;

    private CtmLookup voluntaryexcessField;

    private Hazards hazardsField;

    /// <remarks/>
    public CtmLookup claimfreeyears
    {
        get
        {
            return this.claimfreeyearsField;
        }
        set
        {
            this.claimfreeyearsField = value;
        }
    }

    /// <remarks/>
    public string suminsured
    {
        get
        {
            return this.suminsuredField;
        }
        set
        {
            this.suminsuredField = value;
        }
    }

    /// <remarks/>
    public bool accidentaldamage
    {
        get
        {
            return this.accidentaldamageField;
        }
        set
        {
            this.accidentaldamageField = value;
        }
    }

    /// <remarks/>
    public CtmLookup voluntaryexcess
    {
        get
        {
            return this.voluntaryexcessField;
        }
        set
        {
            this.voluntaryexcessField = value;
        }
    }

    /// <remarks/>
    public Hazards hazards
    {
        get
        {
            return this.hazardsField;
        }
        set
        {
            this.hazardsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class HouseholdClaim
{

    private CtmLookup typeField;

    private CtmLookup causeField;

    private System.DateTime dateField;

    private string costField;

    private bool sameaddressField;

    /// <remarks/>
    public CtmLookup type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public CtmLookup cause
    {
        get
        {
            return this.causeField;
        }
        set
        {
            this.causeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    public string cost
    {
        get
        {
            return this.costField;
        }
        set
        {
            this.costField = value;
        }
    }

    /// <remarks/>
    public bool sameaddress
    {
        get
        {
            return this.sameaddressField;
        }
        set
        {
            this.sameaddressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Residents
{

    private CtmLookup typeField;

    private int nonfamilymembersField;

    private int childrenField;

    private int adultsField;

    private bool catsordogsField;

    private bool smokersField;

    private bool criminalconvictionsField;

    private bool bankruptField;

    private bool insurancerefusedField;

    private HouseholdClaim[] claimsField;

    private int totalField;

    private bool totalFieldSpecified;

    /// <remarks/>
    public CtmLookup type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public int nonfamilymembers
    {
        get
        {
            return this.nonfamilymembersField;
        }
        set
        {
            this.nonfamilymembersField = value;
        }
    }

    /// <remarks/>
    public int children
    {
        get
        {
            return this.childrenField;
        }
        set
        {
            this.childrenField = value;
        }
    }

    /// <remarks/>
    public int adults
    {
        get
        {
            return this.adultsField;
        }
        set
        {
            this.adultsField = value;
        }
    }

    /// <remarks/>
    public bool catsordogs
    {
        get
        {
            return this.catsordogsField;
        }
        set
        {
            this.catsordogsField = value;
        }
    }

    /// <remarks/>
    public bool smokers
    {
        get
        {
            return this.smokersField;
        }
        set
        {
            this.smokersField = value;
        }
    }

    /// <remarks/>
    public bool criminalconvictions
    {
        get
        {
            return this.criminalconvictionsField;
        }
        set
        {
            this.criminalconvictionsField = value;
        }
    }

    /// <remarks/>
    public bool bankrupt
    {
        get
        {
            return this.bankruptField;
        }
        set
        {
            this.bankruptField = value;
        }
    }

    /// <remarks/>
    public bool insurancerefused
    {
        get
        {
            return this.insurancerefusedField;
        }
        set
        {
            this.insurancerefusedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("claim", IsNullable = false)]
    public HouseholdClaim[] claims
    {
        get
        {
            return this.claimsField;
        }
        set
        {
            this.claimsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int total
    {
        get
        {
            return this.totalField;
        }
        set
        {
            this.totalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalSpecified
    {
        get
        {
            return this.totalFieldSpecified;
        }
        set
        {
            this.totalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class OccupiedDetails
{

    private string maxunoccupieddurationField;

    private CtmLookup occupancytypeField;

    /// <remarks/>
    public string maxunoccupiedduration
    {
        get
        {
            return this.maxunoccupieddurationField;
        }
        set
        {
            this.maxunoccupieddurationField = value;
        }
    }

    /// <remarks/>
    public CtmLookup occupancytype
    {
        get
        {
            return this.occupancytypeField;
        }
        set
        {
            this.occupancytypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class UnoccupiedDetails
{

    private CtmLookup reasonField;

    private CtmLookup periodField;

    /// <remarks/>
    public CtmLookup reason
    {
        get
        {
            return this.reasonField;
        }
        set
        {
            this.reasonField = value;
        }
    }

    /// <remarks/>
    public CtmLookup period
    {
        get
        {
            return this.periodField;
        }
        set
        {
            this.periodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class PropertyUse
{

    private CtmLookup occupancystatusField;

    private int howlonglivedatpropertyField;

    private CtmLookup businessuseField;

    private bool childrenmindedatpropertyField;

    private UnoccupiedDetails unoccupieddetailsField;

    private OccupiedDetails occupieddetailsField;

    /// <remarks/>
    public CtmLookup occupancystatus
    {
        get
        {
            return this.occupancystatusField;
        }
        set
        {
            this.occupancystatusField = value;
        }
    }

    /// <remarks/>
    public int howlonglivedatproperty
    {
        get
        {
            return this.howlonglivedatpropertyField;
        }
        set
        {
            this.howlonglivedatpropertyField = value;
        }
    }

    /// <remarks/>
    public CtmLookup businessuse
    {
        get
        {
            return this.businessuseField;
        }
        set
        {
            this.businessuseField = value;
        }
    }

    /// <remarks/>
    public bool childrenmindedatproperty
    {
        get
        {
            return this.childrenmindedatpropertyField;
        }
        set
        {
            this.childrenmindedatpropertyField = value;
        }
    }

    /// <remarks/>
    public UnoccupiedDetails unoccupieddetails
    {
        get
        {
            return this.unoccupieddetailsField;
        }
        set
        {
            this.unoccupieddetailsField = value;
        }
    }

    /// <remarks/>
    public OccupiedDetails occupieddetails
    {
        get
        {
            return this.occupieddetailsField;
        }
        set
        {
            this.occupieddetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class PropertyRooms
{

    private CtmLookup bedroomsField;

    private CtmLookup bathroomsField;

    private CtmLookup receptionsField;

    private CtmLookup otherField;

    private int totalField;

    private bool totalFieldSpecified;

    /// <remarks/>
    public CtmLookup bedrooms
    {
        get
        {
            return this.bedroomsField;
        }
        set
        {
            this.bedroomsField = value;
        }
    }

    /// <remarks/>
    public CtmLookup bathrooms
    {
        get
        {
            return this.bathroomsField;
        }
        set
        {
            this.bathroomsField = value;
        }
    }

    /// <remarks/>
    public CtmLookup receptions
    {
        get
        {
            return this.receptionsField;
        }
        set
        {
            this.receptionsField = value;
        }
    }

    /// <remarks/>
    public CtmLookup other
    {
        get
        {
            return this.otherField;
        }
        set
        {
            this.otherField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int total
    {
        get
        {
            return this.totalField;
        }
        set
        {
            this.totalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalSpecified
    {
        get
        {
            return this.totalFieldSpecified;
        }
        set
        {
            this.totalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class PropertyConstruction
{

    private CtmLookup typeField;

    private CtmLookup wallconstructionField;

    private CtmLookup roofconstructionField;

    private CtmLookup flatroofField;

    private string yearbuiltField;

    private bool separatelockableentranceField;

    /// <remarks/>
    public CtmLookup type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public CtmLookup wallconstruction
    {
        get
        {
            return this.wallconstructionField;
        }
        set
        {
            this.wallconstructionField = value;
        }
    }

    /// <remarks/>
    public CtmLookup roofconstruction
    {
        get
        {
            return this.roofconstructionField;
        }
        set
        {
            this.roofconstructionField = value;
        }
    }

    /// <remarks/>
    public CtmLookup flatroof
    {
        get
        {
            return this.flatroofField;
        }
        set
        {
            this.flatroofField = value;
        }
    }

    /// <remarks/>
    public string yearbuilt
    {
        get
        {
            return this.yearbuiltField;
        }
        set
        {
            this.yearbuiltField = value;
        }
    }

    /// <remarks/>
    public bool separatelockableentrance
    {
        get
        {
            return this.separatelockableentranceField;
        }
        set
        {
            this.separatelockableentranceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Property
{

    private AbiLookup ownershipstatusField;

    private bool smokedetectorsField;

    private AbiLookup listedField;

    private bool goodstateofrepairField;

    private Address riskaddressField;

    private PropertyConstruction constructionField;

    private PropertyRooms roomsField;

    private PropertyUse useField;

    private Residents residentsField;

    /// <remarks/>
    public AbiLookup ownershipstatus
    {
        get
        {
            return this.ownershipstatusField;
        }
        set
        {
            this.ownershipstatusField = value;
        }
    }

    /// <remarks/>
    public bool smokedetectors
    {
        get
        {
            return this.smokedetectorsField;
        }
        set
        {
            this.smokedetectorsField = value;
        }
    }

    /// <remarks/>
    public AbiLookup listed
    {
        get
        {
            return this.listedField;
        }
        set
        {
            this.listedField = value;
        }
    }

    /// <remarks/>
    public bool goodstateofrepair
    {
        get
        {
            return this.goodstateofrepairField;
        }
        set
        {
            this.goodstateofrepairField = value;
        }
    }

    /// <remarks/>
    public Address riskaddress
    {
        get
        {
            return this.riskaddressField;
        }
        set
        {
            this.riskaddressField = value;
        }
    }

    /// <remarks/>
    public PropertyConstruction construction
    {
        get
        {
            return this.constructionField;
        }
        set
        {
            this.constructionField = value;
        }
    }

    /// <remarks/>
    public PropertyRooms rooms
    {
        get
        {
            return this.roomsField;
        }
        set
        {
            this.roomsField = value;
        }
    }

    /// <remarks/>
    public PropertyUse use
    {
        get
        {
            return this.useField;
        }
        set
        {
            this.useField = value;
        }
    }

    /// <remarks/>
    public Residents residents
    {
        get
        {
            return this.residentsField;
        }
        set
        {
            this.residentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Address
{

    private string addressline1Field;

    private string addressline2Field;

    private string addressline3Field;

    private string addressline4Field;

    private string postcodeField;

    /// <remarks/>
    public string addressline1
    {
        get
        {
            return this.addressline1Field;
        }
        set
        {
            this.addressline1Field = value;
        }
    }

    /// <remarks/>
    public string addressline2
    {
        get
        {
            return this.addressline2Field;
        }
        set
        {
            this.addressline2Field = value;
        }
    }

    /// <remarks/>
    public string addressline3
    {
        get
        {
            return this.addressline3Field;
        }
        set
        {
            this.addressline3Field = value;
        }
    }

    /// <remarks/>
    public string addressline4
    {
        get
        {
            return this.addressline4Field;
        }
        set
        {
            this.addressline4Field = value;
        }
    }

    /// <remarks/>
    public string postcode
    {
        get
        {
            return this.postcodeField;
        }
        set
        {
            this.postcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class ContactDetails
{

    private string emailaddressField;

    private string telephonenumberField;

    private Address correspondenceaddressField;

    private CtmLookup addressdifferentreasonField;

    /// <remarks/>
    public string emailaddress
    {
        get
        {
            return this.emailaddressField;
        }
        set
        {
            this.emailaddressField = value;
        }
    }

    /// <remarks/>
    public string telephonenumber
    {
        get
        {
            return this.telephonenumberField;
        }
        set
        {
            this.telephonenumberField = value;
        }
    }

    /// <remarks/>
    public Address correspondenceaddress
    {
        get
        {
            return this.correspondenceaddressField;
        }
        set
        {
            this.correspondenceaddressField = value;
        }
    }

    /// <remarks/>
    public CtmLookup addressdifferentreason
    {
        get
        {
            return this.addressdifferentreasonField;
        }
        set
        {
            this.addressdifferentreasonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Occupation
{

    private AbiLookup occupationField;

    private AbiLookup businesstypeField;

    private bool parttimeField;

    /// <remarks/>
    public AbiLookup occupation
    {
        get
        {
            return this.occupationField;
        }
        set
        {
            this.occupationField = value;
        }
    }

    /// <remarks/>
    public AbiLookup businesstype
    {
        get
        {
            return this.businesstypeField;
        }
        set
        {
            this.businesstypeField = value;
        }
    }

    /// <remarks/>
    public bool parttime
    {
        get
        {
            return this.parttimeField;
        }
        set
        {
            this.parttimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class Employment
{

    private AbiLookup employmentstatusField;

    private Occupation primaryoccupationField;

    private Occupation secondaryoccupationField;

    /// <remarks/>
    public AbiLookup employmentstatus
    {
        get
        {
            return this.employmentstatusField;
        }
        set
        {
            this.employmentstatusField = value;
        }
    }

    /// <remarks/>
    public Occupation primaryoccupation
    {
        get
        {
            return this.primaryoccupationField;
        }
        set
        {
            this.primaryoccupationField = value;
        }
    }

    /// <remarks/>
    public Occupation secondaryoccupation
    {
        get
        {
            return this.secondaryoccupationField;
        }
        set
        {
            this.secondaryoccupationField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(JointPolicyHolder))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class PolicyHolder
{

    private CtmLookup titleField;

    private string firstnameField;

    private string lastnameField;

    private System.DateTime dateofbirthField;

    private CtmLookup maritalstatusField;

    private Employment employmentField;

    /// <remarks/>
    public CtmLookup title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    public string firstname
    {
        get
        {
            return this.firstnameField;
        }
        set
        {
            this.firstnameField = value;
        }
    }

    /// <remarks/>
    public string lastname
    {
        get
        {
            return this.lastnameField;
        }
        set
        {
            this.lastnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime dateofbirth
    {
        get
        {
            return this.dateofbirthField;
        }
        set
        {
            this.dateofbirthField = value;
        }
    }

    /// <remarks/>
    public CtmLookup maritalstatus
    {
        get
        {
            return this.maritalstatusField;
        }
        set
        {
            this.maritalstatusField = value;
        }
    }

    /// <remarks/>
    public Employment employment
    {
        get
        {
            return this.employmentField;
        }
        set
        {
            this.employmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class JointPolicyHolder : PolicyHolder
{

    private CtmLookup relationshipField;

    /// <remarks/>
    public CtmLookup relationship
    {
        get
        {
            return this.relationshipField;
        }
        set
        {
            this.relationshipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://comparethemarket.com/interface/home/v2.0/")]
public partial class PolicyHolders
{

    private PolicyHolder primarypolicyholderField;

    private JointPolicyHolder secondarypolicyholderField;

    /// <remarks/>
    public PolicyHolder primarypolicyholder
    {
        get
        {
            return this.primarypolicyholderField;
        }
        set
        {
            this.primarypolicyholderField = value;
        }
    }

    /// <remarks/>
    public JointPolicyHolder secondarypolicyholder
    {
        get
        {
            return this.secondarypolicyholderField;
        }
        set
        {
            this.secondarypolicyholderField = value;
        }
    }
}
